### Example Notebook

In [2]:
import pandas as pd
pd.__version__

'3.0.2'

In [3]:
students = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'quiz': [85, 90, 78, 92, 18],
    'mid': [88, 85, 80, 95, 20],
    'final': [90, 87, 82, 96, 18],
    'attendance': [9, 9, 8, 8, 5]
}

df = pd.DataFrame(students)
df

      Name  quiz  mid  final  attendance
0    Alice    85   88     90           9
1      Bob    90   85     87           9
2  Charlie    78   80     82           8
3    David    92   95     96           8
4      Eve    18   20     18           5

In [4]:
#df.head()
df.head(3)

      Name  quiz  mid  final  attendance
0    Alice    85   88     90           9
1      Bob    90   85     87           9
2  Charlie    78   80     82           8

In [5]:
df.tail(2)

    Name  quiz  mid  final  attendance
3  David    92   95     96           8
4    Eve    18   20     18           5

In [6]:
df.iloc[1:4]

      Name  quiz  mid  final  attendance
1      Bob    90   85     87           9
2  Charlie    78   80     82           8
3    David    92   95     96           8

In [7]:
df.shape

(5, 5)

In [8]:
df.columns

Index(['Name', 'quiz', 'mid', 'final', 'attendance'], dtype='str')

In [9]:
df.dtypes

Name            str
quiz          int64
mid           int64
final         int64
attendance    int64
dtype: object

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   quiz        5 non-null      int64
 2   mid         5 non-null      int64
 3   final       5 non-null      int64
 4   attendance  5 non-null      int64
dtypes: int64(4), str(1)
memory usage: 332.0 bytes

In [11]:
df.describe()

            quiz        mid     final  attendance
count   5.000000   5.000000   5.00000    5.000000
mean   72.600000  73.600000  74.60000    7.800000
std    30.996774  30.451601  32.04372    1.643168
min    18.000000  20.000000  18.00000    5.000000
25%    78.000000  80.000000  82.00000    8.000000
50%    85.000000  85.000000  87.00000    8.000000
75%    90.000000  88.000000  90.00000    9.000000
max    92.000000  95.000000  96.00000    9.000000

In [12]:
df['total'] = df['quiz'] + df['mid'] + df['final'] + df['attendance']
df

      Name  quiz  mid  final  attendance  total
0    Alice    85   88     90           9    272
1      Bob    90   85     87           9    271
2  Charlie    78   80     82           8    248
3    David    92   95     96           8    291
4      Eve    18   20     18           5     61

In [13]:
df['average'] = df[['quiz', 'mid', 'final', 'attendance']].mean(axis=1)
df['passed'] = df['average'] >= 50
df

      Name  quiz  mid  final  attendance  total  average  passed
0    Alice    85   88     90           9    272    68.00    True
1      Bob    90   85     87           9    271    67.75    True
2  Charlie    78   80     82           8    248    62.00    True
3    David    92   95     96           8    291    72.75    True
4      Eve    18   20     18           5     61    15.25   False

In [14]:
df[df['passed'] == True]

      Name  quiz  mid  final  attendance  total  average  passed
0    Alice    85   88     90           9    272    68.00    True
1      Bob    90   85     87           9    271    67.75    True
2  Charlie    78   80     82           8    248    62.00    True
3    David    92   95     96           8    291    72.75    True

In [15]:
df[df['attendance'] < 6]

  Name  quiz  mid  final  attendance  total  average  passed
4  Eve    18   20     18           5     61    15.25   False

In [16]:
df[['Name', 'average', 'passed']]

      Name  average  passed
0    Alice    68.00    True
1      Bob    67.75    True
2  Charlie    62.00    True
3    David    72.75    True
4      Eve    15.25   False

In [17]:
df.sort_values(by='average', ascending=False)

      Name  quiz  mid  final  attendance  total  average  passed
3    David    92   95     96           8    291    72.75    True
0    Alice    85   88     90           9    272    68.00    True
1      Bob    90   85     87           9    271    67.75    True
2  Charlie    78   80     82           8    248    62.00    True
4      Eve    18   20     18           5     61    15.25   False

In [18]:
df.to_csv('students.csv', index=False)