### This is a sample file for showing pandas operations in markdown format.

In [1]:
import pandas as pd
pd.__version__

'3.0.2'

In [2]:
data = {
    'name': ['Alice', 'Bob', 'Charlie', 'Ash', 'Asif'],
    'quiz': [85, 10, 78, 92, 88],
    'mid': [80, 15, 82, 88, 90],
    'final': [90, 12, 85, 95, 91],
    'attendance': [10, 9, 8, 10, 9]
}

df = pd.DataFrame(data)
df

      name  quiz  mid  final  attendance
0    Alice    85   80     90          10
1      Bob    10   15     12           9
2  Charlie    78   82     85           8
3      Ash    92   88     95          10
4     Asif    88   90     91           9

In [3]:
df.head() # Print the first 5 rows of the dataframe

      name  quiz  mid  final  attendance
0    Alice    85   80     90          10
1      Bob    10   15     12           9
2  Charlie    78   82     85           8
3      Ash    92   88     95          10
4     Asif    88   90     91           9

In [4]:
df.head(3) # Print the first 3 rows of the dataframe

      name  quiz  mid  final  attendance
0    Alice    85   80     90          10
1      Bob    10   15     12           9
2  Charlie    78   82     85           8

In [5]:
df.tail(2) # Print the last 2 rows of the dataframe

   name  quiz  mid  final  attendance
3   Ash    92   88     95          10
4  Asif    88   90     91           9

In [6]:
df.shape # Get the number of rows and columns in the dataframe

(5, 5)

In [7]:
df.columns # Get the column names of the dataframe

Index(['name', 'quiz', 'mid', 'final', 'attendance'], dtype='str')

In [8]:
df.dtypes # Get the data types of each column in the dataframe

name            str
quiz          int64
mid           int64
final         int64
attendance    int64
dtype: object

In [9]:
df.info() # Get a concise summary of the dataframe, including data types and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   quiz        5 non-null      int64
 2   mid         5 non-null      int64
 3   final       5 non-null      int64
 4   attendance  5 non-null      int64
dtypes: int64(4), str(1)
memory usage: 332.0 bytes

In [10]:
df.describe() # Get summary statistics for the numeric columns in the dataframe

            quiz        mid      final  attendance
count   5.000000   5.000000   5.000000     5.00000
mean   70.600000  71.000000  74.600000     9.20000
std    34.260765  31.575307  35.175275     0.83666
min    10.000000  15.000000  12.000000     8.00000
25%    78.000000  80.000000  85.000000     9.00000
50%    85.000000  82.000000  90.000000     9.00000
75%    88.000000  88.000000  91.000000    10.00000
max    92.000000  90.000000  95.000000    10.00000

In [11]:
df['total'] = df['quiz'] + df['mid'] + df['final'] + df['attendance']
df['average'] = df[['quiz', 'mid', 'final', 'attendance']].mean(axis=1)
df['passed'] = df['average'] >= 50
df

      name  quiz  mid  final  attendance  total  average  passed
0    Alice    85   80     90          10    265    66.25    True
1      Bob    10   15     12           9     46    11.50   False
2  Charlie    78   82     85           8    253    63.25    True
3      Ash    92   88     95          10    285    71.25    True
4     Asif    88   90     91           9    278    69.50    True

In [12]:
df[df['passed'] == True]

      name  quiz  mid  final  attendance  total  average  passed
0    Alice    85   80     90          10    265    66.25    True
2  Charlie    78   82     85           8    253    63.25    True
3      Ash    92   88     95          10    285    71.25    True
4     Asif    88   90     91           9    278    69.50    True

In [13]:
df[df['attendance'] < 9]

      name  quiz  mid  final  attendance  total  average  passed
2  Charlie    78   82     85           8    253    63.25    True

In [14]:
df[['name', 'average']]

      name  average
0    Alice    66.25
1      Bob    11.50
2  Charlie    63.25
3      Ash    71.25
4     Asif    69.50

In [16]:
df.sort_values(by='average', ascending=False)

      name  quiz  mid  final  attendance  total  average  passed
3      Ash    92   88     95          10    285    71.25    True
4     Asif    88   90     91           9    278    69.50    True
0    Alice    85   80     90          10    265    66.25    True
2  Charlie    78   82     85           8    253    63.25    True
1      Bob    10   15     12           9     46    11.50   False

In [17]:
df

      name  quiz  mid  final  attendance  total  average  passed
0    Alice    85   80     90          10    265    66.25    True
1      Bob    10   15     12           9     46    11.50   False
2  Charlie    78   82     85           8    253    63.25    True
3      Ash    92   88     95          10    285    71.25    True
4     Asif    88   90     91           9    278    69.50    True

In [18]:
df.to_csv('students.csv', index=True)