### Example Notebook

In [1]:
import pandas as pd
pd.__version__

'3.0.2'

In [2]:
students = {
    "name": ['John', 'Bob', 'Eve', 'Eric', 'Jane'],
    "quiz": [90, 92, 96, 91, 14],
    "mid": [91, 92, 94, 96, 12],
    "final": [88, 91, 93, 99, 13],
    "attendance": [9, 9, 8, 9, 5]
}

df  = pd.DataFrame(students)
df

   name  quiz  mid  final  attendance
0  John    90   91     88           9
1   Bob    92   92     91           9
2   Eve    96   94     93           8
3  Eric    91   96     99           9
4  Jane    14   12     13           5

In [4]:
#df.head()
df.head(3)

   name  quiz  mid  final  attendance
0  John    90   91     88           9
1   Bob    92   92     91           9
2   Eve    96   94     93           8

In [5]:
df.tail(2)

   name  quiz  mid  final  attendance
3  Eric    91   96     99           9
4  Jane    14   12     13           5

In [6]:
df.shape

(5, 5)

In [7]:
df.columns

Index(['name', 'quiz', 'mid', 'final', 'attendance'], dtype='str')

In [8]:
df.dtypes

name            str
quiz          int64
mid           int64
final         int64
attendance    int64
dtype: object

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        5 non-null      str
 1   quiz        5 non-null      int64
 2   mid         5 non-null      int64
 3   final       5 non-null      int64
 4   attendance  5 non-null      int64
dtypes: int64(4), str(1)
memory usage: 332.0 bytes

In [10]:
df.describe()

            quiz        mid      final  attendance
count   5.000000   5.000000   5.000000    5.000000
mean   76.600000  77.000000  76.800000    8.000000
std    35.068504  36.386811  35.891503    1.732051
min    14.000000  12.000000  13.000000    5.000000
25%    90.000000  91.000000  88.000000    8.000000
50%    91.000000  92.000000  91.000000    9.000000
75%    92.000000  94.000000  93.000000    9.000000
max    96.000000  96.000000  99.000000    9.000000

In [12]:
df['total'] = df['quiz'] + df['mid'] + df['final'] + df['attendance']
df['average'] = df[['quiz', 'mid', 'final']].mean(axis=1)
df['passed'] = df['average'] >= 50
df

   name  quiz  mid  final  attendance  total    average  passed
0  John    90   91     88           9    278  89.666667    True
1   Bob    92   92     91           9    284  91.666667    True
2   Eve    96   94     93           8    291  94.333333    True
3  Eric    91   96     99           9    295  95.333333    True
4  Jane    14   12     13           5     44  13.000000   False

In [14]:
df[df['passed'] == True]

   name  quiz  mid  final  attendance  total    average  passed
0  John    90   91     88           9    278  89.666667    True
1   Bob    92   92     91           9    284  91.666667    True
2   Eve    96   94     93           8    291  94.333333    True
3  Eric    91   96     99           9    295  95.333333    True

In [15]:
df[df['attendance'] < 6]

   name  quiz  mid  final  attendance  total  average  passed
4  Jane    14   12     13           5     44     13.0   False

In [16]:
df[['name', 'average', 'passed']]

   name    average  passed
0  John  89.666667    True
1   Bob  91.666667    True
2   Eve  94.333333    True
3  Eric  95.333333    True
4  Jane  13.000000   False

In [17]:
df.sort_values(by='average', ascending=False)

   name  quiz  mid  final  attendance  total    average  passed
3  Eric    91   96     99           9    295  95.333333    True
2   Eve    96   94     93           8    291  94.333333    True
1   Bob    92   92     91           9    284  91.666667    True
0  John    90   91     88           9    278  89.666667    True
4  Jane    14   12     13           5     44  13.000000   False

In [18]:
df.to_csv('students.csv', index=False)