### This is a sample example .ipynb file for running pandas code in a Jupyter notebook.

In [1]:
import pandas as pd
print(pd.__version__)

3.0.2

### Dataframe is a 2-dimensional labeled data structure with columns of potentially different types. It is similar to a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object.

In [2]:
# Example of dataframe.
data ={
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'quiz': [85, 10, 78, 92, 88],
    'mid': [80, 15, 75, 90, 82],
    'final': [90, 15, 80, 88, 91],
    'attendance': [10, 2, 8, 10, 9]
}

students_df = pd.DataFrame(data)
print(students_df)

      Name  quiz  mid  final  attendance
0    Alice    85   80     90          10
1      Bob    10   15     15           2
2  Charlie    78   75     80           8
3    David    92   90     88          10
4      Eve    88   82     91           9

In [3]:
# Basic inspections
print(students_df.head())  # First 5 rows
print(students_df.head(3))  # First 3 rows
print(students_df.tail(2))  # Last 2 rows

      Name  quiz  mid  final  attendance
0    Alice    85   80     90          10
1      Bob    10   15     15           2
2  Charlie    78   75     80           8
3    David    92   90     88          10
4      Eve    88   82     91           9
      Name  quiz  mid  final  attendance
0    Alice    85   80     90          10
1      Bob    10   15     15           2
2  Charlie    78   75     80           8
    Name  quiz  mid  final  attendance
3  David    92   90     88          10
4    Eve    88   82     91           9

In [4]:
print(students_df.shape)  # Number of rows and columns
print(students_df.columns)  # Column names
print(students_df.dtypes)  # Data types of each column

(5, 5)
Index(['Name', 'quiz', 'mid', 'final', 'attendance'], dtype='str')
Name            str
quiz          int64
mid           int64
final         int64
attendance    int64
dtype: object

In [5]:
print(students_df.info())  # Summary of the DataFrame
print(students_df.describe())  # Statistical summary of numerical columns

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   quiz        5 non-null      int64
 2   mid         5 non-null      int64
 3   final       5 non-null      int64
 4   attendance  5 non-null      int64
dtypes: int64(4), str(1)
memory usage: 332.0 bytes
None
            quiz        mid     final  attendance
count   5.000000   5.000000   5.00000     5.00000
mean   70.600000  68.400000  72.80000     7.80000
std    34.260765  30.336447  32.59908     3.34664
min    10.000000  15.000000  15.00000     2.00000
25%    78.000000  75.000000  80.00000     8.00000
50%    85.000000  80.000000  88.00000     9.00000
75%    88.000000  82.000000  90.00000    10.00000
max    92.000000  90.000000  91.00000    10.00000

In [6]:
# Creating new columns
students_df["total"] = students_df["quiz"] + students_df["mid"] + students_df["final"]
students_df["average"] = students_df[['quiz', 'mid', 'final']].mean(axis=1) # axis=1 means we want to calculate the mean across columns for each row.
students_df['passed'] = students_df['average'] >= 50
students_df['passed_status'] = students_df['passed'].map({True: 'Passed', False: 'Failed'})
print(students_df)

      Name  quiz  mid  final  attendance  total    average  passed  \
0    Alice    85   80     90          10    255  85.000000    True
1      Bob    10   15     15           2     40  13.333333   False
2  Charlie    78   75     80           8    233  77.666667    True
3    David    92   90     88          10    270  90.000000    True
4      Eve    88   82     91           9    261  87.000000    True

  passed_status
0        Passed
1        Failed
2        Passed
3        Passed
4        Passed

In [7]:
# Filtering data
students_df[students_df['passed'] == True]
students_df[students_df['attendance'] < 5]
# Only selecting specific columns
students_df[['Name', 'average', 'passed_status']]

      Name    average passed_status
0    Alice  85.000000        Passed
1      Bob  13.333333        Failed
2  Charlie  77.666667        Passed
3    David  90.000000        Passed
4      Eve  87.000000        Passed

In [8]:
students_df.sort_values(by='average', ascending=False)

,Name,quiz,mid,final,attendance,total,average,passed,passed_status
3,David,92,90,88,10,270,90.000000,True,Passed
4,Eve,88,82,91,9,261,87.000000,True,Passed
0,Alice,85,80,90,10,255,85.000000,True,Passed
2,Charlie,78,75,80,8,233,77.666667,True,Passed
1,Bob,10,15,15,2,40,13.333333,False,Failed

In [9]:
students_df.to_csv('students_results.xlsx', index=False)